Repository zsh-users/zsh-completions, pull requests merged in 2018-11, with the labels that each got.

#604 Follow to PR #601: still one typo
  src/_trash-put
Labels: Improvement

#547 improve tmuxp load completions
  src/_tmuxp
Labels: Bug

#609 Add _nft (iptables successor) completion
  src/_nftables
Labels: New compdef

#608 Delete some compdefs that have been included in zsh
  CONTRIBUTING.md
  src/_ack
  src/_ansible
  src/_ansible-galaxy
  src/_ansible-playbook
  src/_ansible-vault
  src/_chattr
  src/_column
  src/_geany
  src/_jq
  src/_lsattr
  src/_lsblk
  src/_scons
  src/_shutdown
  src/_smartmontools
  src/_vpnc
Labels: Task, Upstream

#612 Update medium related commands for VBoxManage
  src/_virtualbox
Labels: Improvement
