Repository zsh-users/zsh-completions, pull requests merged in 2018-10, with the labels that each got.

#599 Completions How To's Typo Fix So second _regex_arguments example works
  zsh-completions-howto.org
Labels: Doc

#588 Add completion script for wireguard's wg-quick
  src/_wg-quick
Labels: New compdef

#600 [golang] add buildmode completion
  src/_golang
Labels: Improvement
