Repository zsh-users/zsh-completions, pull requests merged in 2019-06, with the labels that each got.

#634 Completion function for nano editor!
  src/_nano
Labels: New compdef

#635 hardcode location of command stat for macOS
  src/_vagrant
Labels: Improvement

#636 provide CMAKE_<LANG>_COMPILER_LAUNCHER in cmake completion
  src/_cmake
Labels: Improvement

#637 [cmake] complete CMAKE_GENERATOR environment variable values
  src/_cmake
Labels: Improvement

#638 Fix a syntax error on the PostgreSQL `createuser` utility
  src/_pgsql_utils
Labels: Bug
