Repository zsh-users/zsh-completions, pull requests merged in 2019-09, with the labels that each got.

#642 [golang] unify package completion for build and run
  src/_golang
Labels: Improvement

#643 Add completion for inxi
  src/_inxi
Labels: New compdef

#645 Remove _multirust which is replaced by rustup
  src/_multirust
Labels: Task

#646 [golang] prepare for golang 1.13 updates
  src/_golang
Labels: Improvement
