Repository zsh-users/zsh-completions, pull requests merged in 2019-05, with the labels that each got.

#632 add options for 'go test -test.'
  src/_golang
Labels: Improvement

#630 edit README.md: use `$ZSH_CUSTOM` if it exists
  README.md
Labels: Doc

#626 git-flow: remove non-existing subcommand
  src/_git-flow
Labels: Bug

#628 Add pm2 completion
  src/_pm2
Labels: New compdef
