Repository zsh-users/zsh-completions, pull requests merged in 2023-09, with the labels that each got.

#1032 Update supervisorctl completion
  src/_supervisorctl
Labels: Improvement

#1033 Add supervisord completion
  src/_supervisord
Labels: New compdef

#1038 Fix port's cache policy function
  src/_port
Labels: Bug

#1037 Refactoring direnv
  src/_direnv
Labels: Improvement

#1036 Fix broken gtk-launch completion and update
  src/_gtk-launch
Labels: Bug, Improvement

#1040 Fix wrong initial value settings
  src/_flutter
Labels: Bug

#1042 Update node completion to v20.6.0
  src/_node
Labels: Improvement

#1041 Refactoring port
  src/_port
Labels: Improvement

#1043 Update fwupdmgr completion to 1.8.12
  src/_fwupdmgr
Labels: Improvement

#1039 Add completion script for chatblade
  src/_chatblade
Labels: New compdef
