Repository zsh-users/zsh-completions, pull requests merged in 2023-10, with the labels that each got.

#1045 Update rails completion version 7
  src/_rails
Labels: Improvement

#1046 Do not use global variable, use local variable instead
  src/_envdir
Labels: Bug

#1048 Update cppcheck completion for version 2.12
  src/_cppcheck
Labels: Improvement

#1047 Support THC secure-delete
  src/_srm
Labels: Improvement

#1049 Don't set global variable in srm completion
  src/_srm
Labels: Bug

#1051 Add do-release-upgrade completion
  src/_do-release-upgrade
Labels: New compdef

#1053 Update node completion for version 21.0.0
  src/_node
Labels: Update compdef

#1054 Add jest completion
  src/_jest
Labels: New compdef

#1055 Update node.js for version 21.1.0
  src/_node
Labels: Update compdef
